### ISSUE TITLE
Rider with 3 rides from 12/31

### ISSUE THREAD

**Issue by jrenaut** [hozn/freezingsaddles#7]
Getting some complaints that one rider has rides that are clearly from 12/31. Can I just delete them from the database, or are they just going to get pulled back in? Looking at the import script it doesn't look like they'd get selected.

**Comment by hozn** [comment]
Looking into it.

**Comment by hozn** [comment]
Ok, I removed these rides.  I think the problem is that for some reason
those rides come in with a NULL timezone, so I guess my app (or Strava) is
assuming UTC.  I forget whether the filtering happens when we make the
request or when we parse the results.  I will tweak the logic so they don't
get readded tonight.
